### ISSUE TITLE
页面往下跳动 BUG

### ISSUE THREAD

**Issue by kooy** [ruffchain/explorer#3]
https://testnet.ruffchain.com/

当查看超级节点列表时， 每10秒 页面就会往下跳动一下，应该是 ‘最新不可逆区块’ 插入数据导致。

**Comment by kooy** [comment]
Firefox没问题。 Chrome 浏览器， ‘超级节点列表’ 这几个字在页面中间时，开始每10秒自动下滑一次

**Comment by nieheyong** [comment]
> https://testnet.ruffchain.com/
> 
> 当查看超级节点列表时， 每10秒 页面就会往下跳动一下，应该是 ‘最新不可逆区块’ 插入数据导致。

应该是超级节点 “出块中” 切换导致的，这个问题不影响使用，先不做修改
