### ISSUE TITLE
IE & 低版本浏览器无法打开，建议加上 babel-polyfill

### ISSUE THREAD

**Issue by kooy** [ruffchain/explorer#7]
babel-polyfill 可以有效解决浏览器兼容性问题

**Comment by nieheyong** [comment]
项目并未打算支持低版本ie浏览器，并且vue cli 项目默认是有babel-polyfill的

**Comment by nieheyong** [comment]
添加了全局的polyfill,防止部分第三方库没有polyfill [https://github.com/ruffchain/explorer/commit/3f443ad01232fcc5d317e29dbdc23c46d101a38c](https://github.com/ruffchain/explorer/commit/3f443ad01232fcc5d317e29dbdc23c46d101a38c)

**Comment by nieheyong** [comment]
添加了全局的polyfill,防止部分第三方库没有polyfill [https://github.com/ruffchain/explorer/commit/3f443ad01232fcc5d317e29dbdc23c46d101a38c](https://github.com/ruffchain/explorer/commit/3f443ad01232fcc5d317e29dbdc23c46d101a38c)
